name: Node.js CI/CD

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: ./server

      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json

      - name: Set working directory
        id: set-directory
        run: echo "WORKING_DIRECTORY=./server" >> $GITHUB_ENV

      - name: Set NODE_ENV to development
        run: echo "NODE_ENV=development" >> $GITHUB_ENV

      - name: Build
        run: npm build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Test
        run: npm test
        working-directory: ${{ env.WORKING_DIRECTORY }}
