name: On-Push Testing

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Change directory
        run: cd ./server

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Set NODE_ENV to development
        run: echo "NODE_ENV=development" >> $GITHUB_ENV
        working-directory: ./server

      - name: Build
        run: npm build
        working-directory: ./server

      - name: Test
        run: npm test
        working-directory: ./server
